# Class 'MNConnection', 'ConnectionBlock'
# Created 05/10/2020 (version 5.0)
# Modified 11/02/2021 (version 6.0) - Jose Javier Rico Palomo

import json
import os
import sys
from typing import *


class MNConnection:
    """
        Class MNConnection.
        It simulates connections between users and devices. At each start and end of connection, both users and devices must update their information.
        For each connection generated by a user, some resources are consumed, and a blocking situation may occur.

        Attributes
        ----------
        - MNCONN_id [str]: connection identifier.
        - MNCONN_source_id [str]: device source identifier of the connection.
        - MNCONN_peer_id [str]: device peer identifier of the connection.
        - MNCONN_demand [float]: required capacity for satisfy the demand.
        - MNCONN_priority [int]: priority chosen for the traffic model.
        - MNCONN_path [list of str]: path followed by the connection between the source device and the target device.
        - __duration [float]: duration of the connection.
        - __size [float]: size of the connection.
        - __traffic_type [str]: traffic model used for generate the connection.

        Methods
        -------
        - __init__: Constructor. Parametrized the object according to the entered parameters.
        - __str__: information for output by file or by screen of results.
        - to_json: it dumps (in a json file) the values of the class attributes at each time instant.
        - __get_priority (private): it collects the user priority parameter from the entered file.
    """

    MNCONN_id: str = ""  # Example = "MNCONN_1"
    MNCONN_source_id: str = ""  # Example = "UE_3"
    MNCONN_peer_id: str = ""  # Example = "BS_5"
    MNCONN_demand: float = 0.0  # Mbps
    MNCONN_priority: int = 0  # Absolute units
    MNCONN_path: List[str] = []  # Example = ["UE_1", "BS_7", "BS_9"]
    __duration: float = 0.0  # s
    __size: float = 0.0  # Mb
    __traffic_type: str = ""  # traffic model in "TRAFFIC/traffic_models.py" / "random"

    def __init__(self, conn_id: str, source_id: str, peer_id: str, traffic_type: str, size: float, duration: float, priority: int = 0, priority_file_path: str = "SIMULATOR/Configuration/model_config/user_priority.json"):
        """
            'Init' method of the class 'MNConnection'.
            Constructor. Parametrized the object according to the entered parameters.

            :param conn_id: connection identifier -> Example = "MNCONN_1".
            :param source_id: device source identifier of the connection -> Example = "UE_3".
            :param peer_id: device peer identifier of the connection -> Example = "BS_5".
            :param traffic_type: traffic model used for generate the connection -> traffic model in "TRAFFIC/traffic_models.py" / "random".
            :param size: size of the connection (in Mb).
            :param duration: duration of the connection (in s).
            :param* priority: priority chosen for the traffic model (absolute units).
            :param* priority_file_path: path to user priority file. Defaults to "SIMULATOR/Configuration/model_config/user_priority.json".
        """

        self.MNCONN_id = conn_id
        self.MNCONN_source_id = source_id
        self.MNCONN_peer_id = peer_id
        self.MNCONN_path = []
        self.__traffic_type = traffic_type
        self.__duration = duration
        self.__size = size
        self.MNCONN_demand = self.__size * self.__duration

        if priority is MNConnection.__init__.__defaults__[0]:

            try:
                self.MNCONN_priority = self.__get_priority(priority_file_path)

            except FileExistsError as e:  # Catch exception if occurs (if configuration file doesnt exist)
                print(e)
                sys.exit(3)

        else:
            self.MNCONN_priority = priority

    def __str__(self):
        """
            'To-string' method of the class 'MNConnection'.
            Information for output by file or by screen of results.
        """

        l1 = " - id: " + self.MNCONN_id
        l2 = " - Source: " + self.MNCONN_source_id
        l3 = " - Peer: " + self.MNCONN_peer_id
        l4 = " - Demand: " + str(self.MNCONN_demand) + " Mbps"
        l5 = " - Priority: " + str(self.MNCONN_priority)
        l6 = " - Traffic type: " + self.__traffic_type
        l7 = " - Duration" + str(self.__duration) + " s"
        l8 = " - Size: " + str(self.__size) + " Mb"
        l9 = " - Path: " + str(self.MNCONN_path)

        return l1 + "\n" + l2 + "\n" + l3 + "\n" + l4 + "\n" + l5 + "\n" + l6 + l7 + "\n" + l8 + "\n" + l9

    def to_json(self, time: float, file_path: str = "/SIMULATOR/Results/traffic/connections/"):
        """
            It dumps (in a json file) the values of the class attributes at each time instant.

            :param time: time instant (in seconds).
            :param* file_path: path to the folder containing the results files of the users. Defaults to "/SIMULATOR/Results/traffic/connections/".
        """

        data_dump = dict()
        connection_data = dict()

        connection_data["source_id"] = self.MNCONN_source_id
        connection_data["peer_id"] = self.MNCONN_peer_id
        connection_data["traffic_type"] = self.__traffic_type
        connection_data["duration"] = self.__duration
        connection_data["size"] = self.__size
        connection_data["demand"] = self.MNCONN_demand
        connection_data["priority"] = self.MNCONN_priority
        connection_data["path"] = self.MNCONN_path

        data_dump[time] = connection_data

        with open(file_path + self.MNCONN_id, 'a') as json_file:
            json.dump(data_dump, json_file)

    def __get_priority(self, file_path: str):
        """
            It collects the demand priority parameter from the entered file.
            Priority is assigned on the basis of the traffic model.

            :param file_path: path to the folder containing the configuration file of the traffic priority.

            :return [int] priority: assigned priority to demand according to configuration file parameters.

            :raise FileNotFoundError: occurs when the file you want to access does not exist.
        """

        if os.path.isfile(file_path):  # Check if file exist

            with open(file_path) as json_file:
                data = json.load(json_file)
                priority = data["traffic_priority"][self.__traffic_type]

        else:  # If doest exist, raise and exception
            raise FileNotFoundError(file_path)

        return int(priority)


class ConnectionBlock:
    """
        Class ConnectionBlock.
        It collects the process of blocking a connection.
        A blocking occurs when the link does not have sufficient capacity to meet the demand.

        Attributes
        ----------
        - BLOCK_id [str]: block identifier.
        - BLOCK_time [float]: time instant at which block occurs.
        - BLOCK_connection_id [str]: connection identifier that has been blocked.
        - BLOCK_necessary_capacity [float]: capacity that would be needed for this demand to be met.
        - BLOCK_user_id [str]: user that making the connection that has been blocked.

        Methods
        -------
        - __init__: Constructor. Parametrized the object according to the entered parameters.
        - __str__: information for output by file or by screen of results.
        - to_json: it dumps (in a json file) the values of the class attributes at each time instant.
    """

    BLOCK_id: str = ""  # Example = "BLOCK_1"
    BLOCK_time: float = 0.0  # s
    BLOCK_connection_id: str = ""  # Example = "MNCONN_1"
    BLOCK_necessary_capacity: float = 0.0  # Mbps
    BLOCK_user_id: str = ""  # Example = "USER_2"

    def __init__(self, block_id: str, time: float, connection_id: str, user_id: str, necessary_capacity: float):
        """
            'Init' method of the class 'ConnectionBlock'.
            Constructor. Parametrized the object according to the entered parameters.

            :param block_id: block identifier -> Example = "BLOCK_1".
            :param time: time instant at which block occurs (in seconds).
            :param connection_id: connection identifier that has been blocked -> Example = "MNCONN_1".
            :param user_id: capacity that would be needed for this demand to be met (in Mbps).
            :param necessary_capacity: user that making the connection that has been blocked -> Example = "USER_2".
        """

        self.BLOCK_id = block_id
        self.BLOCK_time = time
        self.BLOCK_connection_id = connection_id
        self.BLOCK_necessary_capacity = necessary_capacity
        self.BLOCK_user_id = user_id

    def __str__(self):
        """
            'To-string' method of the subclass 'HandoverLvl2'. Inheritance of abstract class 'Handover'.
            Information for output by file or by screen of results.
        """

        l1 = " - id: " + self.BLOCK_id
        l2 = " - Time: " + str(self.BLOCK_time) + " s"
        l3 = " - Connection blocked: " + self.BLOCK_connection_id
        l4 = " - Necessary capacity: " + str(self.BLOCK_necessary_capacity) + " Mbps"
        l5 = " - User id: " + self.BLOCK_user_id

        return l1+"\n"+l2+"\n"+l3+"\n"+l4+"\n"+l5

    def to_json(self, time: float, file_path: str = "/SIMULATOR/Results/traffic/connections/blocks/"):
        """
            It dumps (in a json file) the values of the class attributes at each time instant.

            :param time: time instant (in seconds).
            :param* file_path: path to the folder containing the results files of the network devices. Defaults to "/SIMULATOR/Results/traffic/connections/blocks/".
        """

        data_dump = dict()
        block_data = dict()

        block_data["time"] = str(self.BLOCK_time)
        block_data["connection_id"] = self.BLOCK_connection_id
        block_data["necessary_capacity"] = str(self.BLOCK_necessary_capacity)
        block_data["user_id"] = self.BLOCK_user_id

        data_dump[time] = block_data

        with open(file_path + "/" + self.BLOCK_connection_id + "/" + self.BLOCK_id, 'a') as json_file:
            json.dump(data_dump, json_file)
