# Class 'NetworkDevice' (abstract), class 'Router'
# Created 13/02/2020 (version 3.0)
# Modified 29/01/2021 (version 6.0) - Jose Javier Rico Palomo

from typing import *
from SIMULATOR.src.CODE_UTILS.exceptions import ConnectionDoesntExist
from SIMULATOR.src.TRAFFIC.connections import MNConnection
import json
from SIMULATOR.src.MODELS.power_models import PowerModel
from SIMULATOR.src.MODELS.economic_models import EconomicModel


class NetworkDevice:
    """
        Abstract class NetworkDevice.
        It simulates the behaviour of a layer 3 (access network) generic device.
        The device can be a Router.

        Attributes
        ----------
        - ND_id [str]: device identifier.
        - ND_economic_model [object (SIMULATOR.EconomicModel)]: economic cost model of the device. Used to calculate the total costs of the device.
        - ND_power_model [object (SIMULATOR.PowerModel)]: power consumption model of the device. Used to calculate the total consumed power of the device.
        - ND_links_fh [array of str]: identifier of the open links of the device with the base stations of the cellular network (fronthaul).
        - ND_links_bh [array of str]: identifier of the open links of the device with others network devices of the access network (backhaul).

        Methods
        -------
        - __str__: information for output by file or by screen of results.
        - to_dict: it creates a dictionary with the values of the object to be used by the subclass to dump the values into a json file.
    """

    ND_id: str = ""  # Example = "ROUTER_1"
    ND_economic_model: EconomicModel = None
    ND_power_model: PowerModel = None
    ND_links_fh: List[str] = []  # Example = ["LINK_1", "LINK_2"]
    ND_links_bh: List[str] = []  # Example = ["LINK_1", "LINK_2"]

    def __str__(self):
        """
            'To-string' method of the abstract class 'NetworkDevice'.
            Information for output by file or by screen of results.
        """

        l1 = " - id " + self.ND_id
        l2 = " - Economic Model: None" if self.ND_economic_model is None else " - Economic Model: " + self.ND_economic_model.EM_id
        l3 = " - Power Model: None" if self.ND_power_model is None else " - Power Model: " + self.ND_power_model.PM_id
        l4 = " - Fronthaul links: None" if len(self.ND_links_fh) == 0 else " - Fronthaul links: " + str(self.ND_links_fh)
        l5 = " - Backhaul links: None" if len(self.ND_links_bh) == 0 else " - Backhaul links: " + str(self.ND_links_bh)

        return l1+"\n"+l2+"\n"+l3+"\n"+l4+"\n"+l5

    def to_dict(self):
        """
            It creates a dictionary with the values of the object to be used by the subclass to dump the values into a json file.
        """

        network_device_data = dict()

        network_device_data["economic_model"] = "None" if self.ND_economic_model is None else self.ND_economic_model.EM_id
        network_device_data["power_model"] = "None" if self.ND_power_model is None else self.ND_power_model.PM_id
        network_device_data["fronthaul_links"] = "None" if len(self.ND_links_fh) == 0 else str(self.ND_links_fh)
        network_device_data["backhaul_links"] = "None" if len(self.ND_links_bh) == 0 else str(self.ND_links_bh)

        return network_device_data


class Router(NetworkDevice):
    """
        Subclass Router. Inheritance of abstract class 'NetworkDevice'.
        It receives the connections generated by the users.
        They are included in the access network (Class 'AccessNetwork').

        Attributes
        ----------
        - ROUTER_resources [int]: available resources on the device at every moment of time. Used to simulate incoming UE connections.
        - ROUTER_active_connections [list of str]: identifier of the active connections in the Router.
        - __initial_resources (private) [int]: initial resources of the devices. Used to simulate incoming UE connections.

        Methods
        -------
        - __init__: Constructor. Parametrized the object according to the entered parameters.
        - __str__: information for output by file or by screen of results.
        - to_json: it dumps (in a json file) the values of the class attributes at each time instant.
        - __add_resources (private): add resources available through the router.
        - __remove_resources (private): remove available resources through the router.
        - __check_block (private): checks whether the device is in a block situation under a specific demand.
        - add_connection: add, if the block doest exist, the incoming connection to the router, by subtracting resources where proceed.
        - remove_connection: remove, if exist, the ended connection, freeing up resources in the device.
    """

    ROUTER_resources: float = 0  # Mbps
    ROUTER_active_connections: List[str] = []  # Example = ["CONN_1", "CONN_2"]
    __initial_resources = 0  # Mbps

    def __init__(self, router_id: str, resources: float, economic_model: Union[None, EconomicModel], power_model: Union[None, PowerModel], fh_links: List[str] = None, bh_links: List[str] = None, active_connections: List[str] = None):
        """
            'Init' method of the subclass 'Router'. Inheritance of abstract class 'NetworkDevice'.
            Constructor. Parametrized the object according to the entered parameters.

            :param router_id: device identifier -> Example = "ROUTER_1".
            :param resources: initial resources of the device (in Mbps).
            :param economic_model: economic cost model of the device. 'None' if do not want to evaluate.
            :param power_model: power model of the device. 'None' if do not want to evaluate.
            :param* fh_links: identifier of the fronthaul links of the device -> Example = ["LINK_1", "LINK_2"]. Defaults to "None".
            :param* bh_links: identifier of the backhaul links of the device -> Example = ["LINK_1", "LINK_2"]. Defaults to "None".
            :param* active_connections: identifier of the active connections in the router -> Example = ["CONN_1", "CONN_2"]. Defaults to "None".
        """

        self.ND_id = router_id  # Superclass attribute
        self.__initial_resources = resources
        self.ROUTER_resources = self.__initial_resources
        self.ND_economic_model = economic_model  # Superclass attribute
        self.ND_power_model = power_model  # Superclass attribute
        self.ND_links_fh = [] if fh_links is None else fh_links  # Superclass attribute
        self.ND_links_bh = [] if bh_links is None else bh_links  # Superclass attribute
        self.ROUTER_active_connections = [] if active_connections is None else active_connections

    def __str__(self):
        """
            'To-string' method of the subclass 'Router'. Inheritance of abstract class 'NetworkDevice'.
            Information for output by file or by screen of results.
        """

        l1 = super().__str__()  # Superclass information
        l2 = " - Initial resources: " + str(self.__initial_resources) + " Mbps."
        l3 = " - Active connections: None" if len(self.ROUTER_active_connections) == 0 else " - Active connections: " + str(self.ROUTER_active_connections)

        return l1+"\n"+l2+"\n"+l3

    def to_json(self, time: float, file_path: str = "/SIMULATOR/Results/access_network/network_devices/"):
        """
            It dumps (in a json file) the values of the class attributes at each time instant.

            :param time: time instant (in seconds).
            :param* file_path: path to the folder containing the results files of the network devices. Defaults to "/SIMULATOR/Results/access_network/network_devices/".
        """

        data_dump = dict()
        router_data = super().to_dict()

        router_data["available_resources"] = str(self.ROUTER_resources)
        router_data["active_connections"] = "None" if len(self.ROUTER_active_connections) == 0 else str(self.ROUTER_active_connections)
        router_data["initial_resources"] = str(self.__initial_resources)

        data_dump[time] = router_data

        with open(file_path + self.ND_id, 'a') as json_file:
            json.dump(data_dump, json_file)

    def __add_resources(self, resources: float):
        """
            Add resources available through the router.
            If want to add more resources than the maximum allowed (initial), only the maximum allowed (with which it is created) is added.
            If the maximum is not exceeded, they are added without restriction.

            :param resources: amount of resources to be added (in Mbps).
        """

        if self.ROUTER_resources + resources > self.__initial_resources:  # If want to add more resources than the maximum allowed
            self.ROUTER_resources = self.__initial_resources  # The maximum allowed (with which it is created) is added

        else:  # If the maximum is not exceeded, the resources are added.
            self.ROUTER_resources = self.ROUTER_resources + resources

    def __remove_resources(self, resources: float):
        """
            Remove available resources through the router.
            It is necessary to check if block exist before remove the resources (outside the method).

            :param resources: amount of resources to be removed (in Mbps).
        """

        if self.ROUTER_resources - resources >= 0:  # If demand can be met, it does so and remove resources
            self.ROUTER_resources = self.ROUTER_resources - resources

    def __check_block(self, resources: float):
        """
            Checks whether the device is in a block situation under a specific demand (measured in resources).
            If the device runs out of resources to meet the demand, there is a block.

            :param resources: amount of demand resources (in Mbps).

            :return [bool] block: router status (whether if has been blocked or not).
        """

        block = False

        if self.ROUTER_resources - resources < 0:  # If the available resources reach zero, the router runs out of resources to meet demands
            block = True

        return block

    def add_connection(self, connection: MNConnection):
        """
            Add, if the block doest exist, the incoming connection to the router, by subtracting resources where proceed.
            If there are no resources available, it warns that the connection will be blocked. The blocked must be checked when the method is called.

            :param connection: incoming connection to the device.

            :return [bool] block: connection status (whether of not is has been ruled out due to lack of resources).
        """

        block = False

        if self.__check_block(connection.MNCONN_demand) is True:  # Check if block exists
            block = True  # If block exist, block the connection

        else:  # If block doesnt exist, add the connection and remove resources from device
            self.__remove_resources(connection.MNCONN_demand)
            self.ROUTER_active_connections.append(connection.MNCONN_id)

        return block

    def remove_connection(self, connection: MNConnection):
        """
            Remove, if exist, the ended connection, freeing up resources in the device.

            :param connection: ended connection.

            :raise ConnectionDoesntExist: occurs when the connection that are trying to remove doesnt exist.
        """

        # Check if the connection are active in the router
        if connection.MNCONN_id in self.ROUTER_active_connections:  # If exist, delete the connection from active_connections array and add resources
            self.ROUTER_active_connections.remove(connection.MNCONN_id)
            self.__add_resources(connection.MNCONN_demand)

        else:  # If doest exist, raise an exception
            raise ConnectionDoesntExist(connection.MNCONN_id)
