# Module 'network_topology'
# Created 13/02/2020 (version 3.0)
# Modified 07/04/2021 (version 6.0) - Jose Javier Rico Palomo

import itertools
import networkx as nx
from networkx.utils import pairwise
from typing import Dict
from SIMULATOR.src.ACCESS_NETWORK.network_device import Router
from SIMULATOR.src.LINKS.link import Link


def generate_access_network_graph(routers: Dict[str, Router]):
    """
        Generates a zero-grade graph, given the layer-3 devices.
        The resulting graph is composed only for nodes, where each router is a single node, and its defined by its identifier.

        :param routers: routers that conform the access network -> key = router id, value = router object.

        :return [object (NetworkX.Graph)] graph: zero-grade graph composed by the routers. Each node its defined by router identifier.
    """

    graph = nx.Graph()

    i = 0
    for R in routers.values():  # Iterates the dict of routers

        graph.add_node(i, name_node=R.ND_id)  # Create a node, which principal attribute is the id of the router
        i += 1

    return graph


def linear_topology(graph: nx.graph):
    """
        Generates a graph for a access network linear topology.
        Linear topology: routers are only connected to their neighbours -> (R1)-----(R2)-----(R3)-----(R4)
        [REF] https://networkx.github.io/documentation/stable/_module/networkx/generators/classic.html#path_graph

        :param graph: zero-grade graph composed by the routers.

        :return Object (NetworkX.Graph)] graph: modified graph with the vertices generated by linear topology.
    """

    graph.add_edges_from(pairwise(graph.nodes))  # path_graph

    return graph


def complete_mesh_topology(graph: nx.graph):
    """
        Generates a graph for a access network complete mesh topology.
        Complete mesh topology: all the layer-3 devices are connected with each others, by a complete mesh.
        [REF] https://networkx.github.io/documentation/stable/_module/networkx/generators/classic.html#complete_graph

        :param graph: zero-grade graph composed by the routers.

        :return Object (NetworkX.Graph)] graph: modified graph with the vertices generated by complete mesh topology.
    """

    edges = itertools.combinations(graph.nodes, 2)  # complete_graph
    graph.add_edges_from(edges)

    return graph

# ----------------------------------------------------------------------------------- #


def configuration_test():
    """
        Predefined configuration for the test of the Access Network module.
        4 routers connected between them, by a closed lineal topology.
        Available resource in the routers: 100 Gbps.
        Link capacity: 100 Gb.

        :return [dict] routers: network devices generated in the predefined topology.
        :return [dict] network: links between the network devices generated in the predefined topology.
        :return [Object (NetworkX.Graph)]: connection graph of the access network (nodes are routers and vertices are links).
    """

    r1_id = "ROUTER_1"
    r2_id = "ROUTER_2"
    r3_id = "ROUTER_3"
    r4_id = "ROUTER_4"

    network = dict()
    graph = nx.Graph()
    routers = dict()

    # NODES
    graph.add_node(0, name_node=r1_id)
    graph.add_node(1, name_node=r2_id)
    graph.add_node(2, name_node=r3_id)
    graph.add_node(3, name_node=r4_id)

    # LINKS
    l1 = Link("AN_LINK_1", r1_id, r2_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l1.LINK_id] = l1
    graph.add_edge(0, 1, name_edge=l1.LINK_id)

    l2 = Link("AN_LINK_2", r2_id, r3_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l2.LINK_id] = l2
    graph.add_edge(1, 2, name_edge=l2.LINK_id)

    l3 = Link("AN_LINK_3", r3_id, r4_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l3.LINK_id] = l3
    graph.add_edge(2, 3, name_edge=l3.LINK_id)

    l4 = Link("AN_LINK_4", r4_id, r1_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l4.LINK_id] = l4
    graph.add_edge(3, 0, name_edge=l4.LINK_id)

    # ROUTERS
    r1 = Router(r1_id, 100000, None, None, bh_links=[l1.LINK_id, l4.LINK_id])
    routers[r1.ND_id] = r1

    r2 = Router(r2_id, 100000, None, None, bh_links=[l1.LINK_id, l3.LINK_id])
    routers[r2.ND_id] = r2

    r3 = Router(r3_id, 100000, None, None, bh_links=[l2.LINK_id, l4.LINK_id])
    routers[r3.ND_id] = r3

    r4 = Router(r4_id, 100000, None, None, bh_links=[l1.LINK_id, l3.LINK_id])
    routers[r4.ND_id] = r4

    return routers, network, graph


def configuration_art1():
    """
        Predefined configuration for the RAN slicing article (IEEE Access).
        [REF] Sergei Nikolaev et al. Pushing the envelope in distributed ns-3 simulations: one billion nodes. In Proceedings of the 2015 Workshop on ns-3 (2015). Association for Computing Machinery, New York, NY, USA, 67–74.
        8 routers in small-world network with k=4 and b=0'5.
        Available resource in the routers: 100 Gbps.
        Link capacity: 100 Gb.

        :return [dict] routers: network devices generated in the predefined topology.
        :return [dict] network: links between the network devices generated in the predefined topology.
        :return [Object (NetworkX.Graph)]: connection graph of the access network (nodes are routers and vertices are links).
    """

    r1_id = "ROUTER_1"
    r2_id = "ROUTER_2"
    r3_id = "ROUTER_3"
    r4_id = "ROUTER_4"
    r5_id = "ROUTER_5"
    r6_id = "ROUTER_6"
    r7_id = "ROUTER_7"
    r8_id = "ROUTER_8"

    network = dict()
    graph = nx.Graph()
    routers = dict()

    # NODES
    graph.add_node(0, name_node=r1_id)
    graph.add_node(1, name_node=r2_id)
    graph.add_node(2, name_node=r3_id)
    graph.add_node(3, name_node=r4_id)
    graph.add_node(4, name_node=r5_id)
    graph.add_node(5, name_node=r6_id)
    graph.add_node(6, name_node=r7_id)
    graph.add_node(7, name_node=r8_id)

    # LINKS
    l1 = Link("AN_LINK_1", r1_id, r2_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l1.LINK_id] = l1
    graph.add_edge(0, 1, name_edge=l1.LINK_id)

    l2 = Link("AN_LINK_2", r1_id, r3_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l2.LINK_id] = l2
    graph.add_edge(0, 2, name_edge=l2.LINK_id)

    l3 = Link("AN_LINK_3", r1_id, r5_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l3.LINK_id] = l3
    graph.add_edge(0, 4, name_edge=l3.LINK_id)

    l4 = Link("AN_LINK_4", r2_id, r3_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l4.LINK_id] = l4
    graph.add_edge(1, 2, name_edge=l4.LINK_id)

    l5 = Link("AN_LINK_5", r2_id, r4_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l5.LINK_id] = l5
    graph.add_edge(1, 3, name_edge=l5.LINK_id)

    l6 = Link("AN_LINK_6", r3_id, r8_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l6.LINK_id] = l6
    graph.add_edge(2, 7, name_edge=l6.LINK_id)

    l7 = Link("AN_LINK_7", r3_id, r6_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l7.LINK_id] = l7
    graph.add_edge(2, 5, name_edge=l7.LINK_id)

    l8 = Link("AN_LINK_8", r3_id, r4_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l8.LINK_id] = l8
    graph.add_edge(2, 3, name_edge=l8.LINK_id)

    l9 = Link("AN_LINK_9", r4_id, r5_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l9.LINK_id] = l9
    graph.add_edge(3, 4, name_edge=l9.LINK_id)

    l10 = Link("AN_LINK_10", r4_id, r6_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l10.LINK_id] = l10
    graph.add_edge(3, 5, name_edge=l10.LINK_id)

    l11 = Link("AN_LINK_11", r4_id, r7_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l11.LINK_id] = l11
    graph.add_edge(3, 6, name_edge=l11.LINK_id)

    l12 = Link("AN_LINK_12", r4_id, r8_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l12.LINK_id] = l12
    graph.add_edge(3, 7, name_edge=l12.LINK_id)

    l13 = Link("AN_LINK_13", r5_id, r6_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l13.LINK_id] = l13
    graph.add_edge(4, 5, name_edge=l13.LINK_id)

    l14 = Link("AN_LINK_14", r5_id, r8_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l14.LINK_id] = l14
    graph.add_edge(4, 7, name_edge=l14.LINK_id)

    l15 = Link("AN_LINK_15", r6_id, r8_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l15.LINK_id] = l15
    graph.add_edge(5, 7, name_edge=l15.LINK_id)

    l16 = Link("AN_LINK_16", r7_id, r8_id, "layer3", 0, capacity=100000)  # 100Gb ethernet
    network[l16.LINK_id] = l16
    graph.add_edge(6, 7, name_edge=l16.LINK_id)

    # ROUTERS
    r1 = Router(r1_id, 100000, None, None, bh_links=[l1.LINK_id, l2.LINK_id, l3.LINK_id])
    routers[r1.ND_id] = r1

    r2 = Router(r2_id, 100000, None, None, bh_links=[l1.LINK_id, l4.LINK_id, l5.LINK_id])
    routers[r2.ND_id] = r2

    r3 = Router(r3_id, 100000, None, None, bh_links=[l2.LINK_id, l4.LINK_id, l6.LINK_id, l7.LINK_id, l8.LINK_id])
    routers[r3.ND_id] = r3

    r4 = Router(r4_id, 100000, None, None, bh_links=[l5.LINK_id, l8.LINK_id, l9.LINK_id, l10.LINK_id, l11.LINK_id, l12.LINK_id])
    routers[r4.ND_id] = r4

    r5 = Router(r5_id, 100000, None, None, bh_links=[l5.LINK_id, l9.LINK_id, l13.LINK_id, l14.LINK_id])
    routers[r5.ND_id] = r5

    r6 = Router(r6_id, 100000, None, None, bh_links=[l7.LINK_id, l10.LINK_id, l13.LINK_id, l15.LINK_id])
    routers[r6.ND_id] = r6

    r7 = Router(r7_id, 100000, None, None, bh_links=[l11.LINK_id, l16.LINK_id])
    routers[r7.ND_id] = r7

    r8 = Router(r8_id, 100000, None, None, bh_links=[l6.LINK_id, l12.LINK_id, l14.LINK_id, l15.LINK_id, l16.LINK_id])
    routers[r8.ND_id] = r8

    return routers, network, graph
