# Module 'point_process'
# Created 06/03/2020 (version 3.0)
# Modified 29/01/2021 (version 6.0) - Jose Javier Rico Palomo

import numpy as np
import scipy.stats
from SIMULATOR.src.CODE_UTILS.exceptions import ConfigurationNotFound, ConditionalParameterIsDefault
from SIMULATOR.src.MATH_UTILS import hard_core_point_process as hcpp
from typing import *


def point_process(pp: str, size: float, alpha: float = 0.0, beta: float = 0.0, sigma: float = 0.0, number_of_points: int = 0, hexagon_points: List[Tuple[float, float]] = None):
    """
        Generates the chosen point process according to the entered parameters.

        :param pp: selected point process.
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).
        :param* alpha: density of the point process (absolute units). Defaults to 0.
        :param* beta: density of the sub point process (absolute units). Defaults to 0.
        :param* sigma: density of the sub point process (absolute units) or distribution radius (in meters). Defaults to 0.
        :param* number_of_points: number of points to be distributed. Defaults to 0.
        :param* hexagon_points: points generated by hexagonal tessellation (for 'poisson_in_hex'). Defaults to None.

        :return [list of list] generated_points: X and Y coordinates of the two-dimensional locations of the generated points -> [(x,y), (x,y), ...].
        If the chosen point process is Matern or Thomas, it will return an array of two position, corresponding to the locations of the macro and small cells, respectively.
        For any other point process, it will return a single-position array.

        :except ConfigurationNotFound: occurs when the configuration entered by parameters is not implemented in the simulator.
        :except ConditionalParameterIsDefault: occurs when the conditional parameters have default values (if the default configuration is not configured).
    """

    if pp == "CR":

        # Check if conditional parameters have the default value
        if number_of_points is point_process.__defaults__[3]:
            raise ConditionalParameterIsDefault("number_of_points")

        points = [random_point_process(number_of_points, size)]

    elif pp == "PPP":

        # Check if conditional parameters have the default value
        if alpha is point_process.__defaults__[0]:
            raise ConditionalParameterIsDefault("alpha")

        points = [poisson_point_process(size, alpha=alpha, number_of_points=number_of_points)]

    elif pp == "BPP":

        # Check if conditional parameters have the default value
        if number_of_points is point_process.__defaults__[3]:
            raise ConditionalParameterIsDefault("number_of_points")

        points = [binomial_point_process(number_of_points, size)]

    elif pp == "HCPP":

        # Check if conditional parameters have the default value
        if sigma is point_process.__defaults__[2]:
            raise ConditionalParameterIsDefault("sigma/radius")

        points = [hard_core_point_process(sigma, size)]

    elif pp == "MPP":

        # Check if conditional parameters have the default value
        if alpha is point_process.__defaults__[0]:
            raise ConditionalParameterIsDefault("alpha")

        if beta is point_process.__defaults__[1]:
            raise ConditionalParameterIsDefault("beta")

        if sigma is point_process.__defaults__[2]:
            raise ConditionalParameterIsDefault("sigma/radius")

        aux_macro_points, aux_small_points = materns_point_process(alpha, beta, sigma, size)
        points = [aux_macro_points, aux_small_points]

    elif pp == "TPP":

        # Check if conditional parameters have the default value
        if alpha is point_process.__defaults__[0]:
            raise ConditionalParameterIsDefault("alpha")

        if beta is point_process.__defaults__[1]:
            raise ConditionalParameterIsDefault("beta")

        if sigma is point_process.__defaults__[2]:
            raise ConditionalParameterIsDefault("sigma/radius")

        aux_macro_points, aux_small_points = thomas_point_process(alpha, beta, sigma, size)
        points = [aux_macro_points, aux_small_points]

    elif pp == "PPP_hex":

        # Check if conditional parameters have the default value
        if alpha is point_process.__defaults__[0]:
            raise ConditionalParameterIsDefault("alpha")

        if sigma is point_process.__defaults__[2]:
            raise ConditionalParameterIsDefault("sigma/radius")

        if number_of_points is point_process.__defaults__[3]:
            raise ConditionalParameterIsDefault("number_of_points")

        points = [poisson_in_hex(hexagon_points, sigma, points_per_hexagon=number_of_points, alpha=alpha)]

    else:
        raise ConfigurationNotFound(pp)

    return points


def random_point_process(number_of_points: int, size: float):
    """
        Generation of a point process distributed in a completely random way (without specific distribution).

        :param number_of_points: number of points to be randomly distributed.
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points, randomly distributed -> [(x,y), (x,y), ...].
    """

    generated_points = np.random.rand(number_of_points, 2)*size

    return generated_points


def poisson_point_process(size: float, alpha: float = 0.0, number_of_points: int = 0):
    """
        Generation of a poisson point process.
        If the number of points is not specified, the density (alpha) is used.
        [REF] http://connor-johnson.com/2014/02/25/spatial-point-processes/
        [REF] D. J. Daley and D. Vere-Jones, An Introduction to the Theory of Point Processes, 2nd ed. Springer, 2003.

        - Consistent values: alpha=10.

        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).
        :param* alpha: density of the point process (absolute units). Defaults to 0.
        :param* number_of_points: number of points to be poisson distributed.. Defaults to 0.

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points, poisson distributed -> [(x,y), (x,y), ...].
    """

    n = scipy.stats.poisson(alpha).rvs() if number_of_points == 0 else number_of_points  # ? In the reference: *size*size

    if n == 0:
        raise ValueError

    x = scipy.stats.uniform.rvs(0, size, (n, 1))
    y = scipy.stats.uniform.rvs(0, size, (n, 1))
    generated_points = np.hstack((x, y))

    return generated_points


def binomial_point_process(number_of_points: int, size: float):
    """
        Generation of a binomial point process.
        [REF] http://connor-johnson.com/2014/02/25/spatial-point-processes/
        [REF] D. J. Daley and D. Vere-Jones, An Introduction to the Theory of Point Processes, 2nd ed. Springer, 2003.

        :param number_of_points: number of points to be binomial distributed.
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points, binomial distributed -> [(x,y), (x,y), ...].
    """

    x = scipy.stats.uniform.rvs(0, size, (number_of_points, 1))
    y = scipy.stats.uniform.rvs(0, size, (number_of_points, 1))

    generated_points = np.hstack((x, y))

    return generated_points


def hard_core_point_process(radius: float, size: float):
    """
        Generation of a hard core point process. It generates points separated by a certain distance between them.
        This method used the file 'MATH_UTILS/hard_core_point_process.py'.
        [REF] http://connor-johnson.com/2014/02/25/spatial-point-processes/
        [REF] J. Teichmann, F. Ballani, and K. van den Boogart, “Generalizations of Matern’s Hard-Core Point Processes,” arXiv, 09 2012.

        :param radius: distance between points (in meters).
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points, hard core distributed -> [(x,y), (x,y), ...].
    """

    grid = hcpp.Grid(radius, size, size)
    random_hcpp = (np.random.uniform(0, size), np.random.uniform(0, size))

    return grid.poisson(random_hcpp)


def materns_point_process(alpha: float, beta: float, radius: float, size: float):
    """
        Generation of a materns point process. It generates cluster by a poisson process. Then, in each region cluster, generates other point process (materns).
        This method used the file 'MATH_UTILS/hard_core_point_process.py'.
        [REF] http://connor-johnson.com/2014/02/25/spatial-point-processes/
        [REF] D. J. Daley and D. Vere-Jones, An Introduction to the Theory of Point Processes, 2nd ed. Springer, 2003.

        - Consistent values:: alpha=10, beta=30, radius=100

        :param alpha: density of the point process for clusters (absolute units).
        :param beta: density of the sub point process (absolute units).
        :param radius: distance between sub-points in a cluster (in meters).
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the clusters, poisson distributed -> [(x,y), (x,y), ...].
        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points (sub clusters), materns distributed -> [(x,y), (x,y), ...].
    """

    generated_points = list()

    poisson_points = poisson_point_process(alpha, size)  # Poisson point process generation (for clusters)

    # Materns point process in each cluster
    for i in range(0, len(poisson_points)):

        n = scipy.stats.poisson(beta).rvs()

        for j in range(n):
            rx, ry = hcpp.uniform_disk(poisson_points[i, 0], poisson_points[i, 1], radius)
            generated_points.append([rx, ry])

    return poisson_points, np.array(generated_points)


def thomas_point_process(alpha: float, beta: float, sigma: float, size: float):
    """
        Generation of a tomas point process. It generates cluster by a poisson process. Then, in each region cluster, generates other point process (thomas).
        [REF] http://connor-johnson.com/2014/02/25/spatial-point-processes/
        [REF] D. J. Daley and D. Vere-Jones, An Introduction to the Theory of Point Processes, 2nd ed. Springer, 2003.

        - Consistent values:: alpha=10, beta=30, sigma=100

        :param alpha: density of the point process for clusters (absolute units).
        :param beta: density of the sub point process (absolute units).
        :param sigma: density of the thomas point process (absolute units).
        :param size: size of one of the sides of the scenario, taking into account square scenarios (in meters).

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the clusters, poisson distributed -> [(x,y), (x,y), ...].
        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points (sub clusters), thomas distributed -> [(x,y), (x,y), ...].
    """

    generated_points = list()

    poisson_points = poisson_point_process(alpha, size)  # Poisson point process generation (for clusters)

    # Thomas point process in each cluster
    for i in range(0, len(poisson_points)):

        n = scipy.stats.poisson(beta).rvs()

        for j in range(n):
            sub_point = scipy.stats.norm(loc=poisson_points[i, :2], scale=(sigma, sigma))
            generated_points.append(list(sub_point.rvs(2)))

    return poisson_points, np.array(generated_points)


def poisson_in_hex(hexagonal_points: List[Tuple[float, float]], sigma: float, points_per_hexagon: int = 0, alpha: float = 0):
    """
        Generation of a poisson point process inside an hexagonal tesselation.
        A practical example would be that macro cells are generated following a hexagonal tessellation and small cells are generated according to a poisson process in each hexagon.

        :param hexagonal_points: points generated by hexagonal tessellation. See 'GEOMETRY/tessellations.py/hexagonal_tessellation'.
        :param sigma: variance of the gaussian distribution used for the point generation in each hexagon (absolute units).
        :param* points_per_hexagon: number of points in each hexagon to be distributed according to poisson process. Defaults to 0.
        :param* alpha: density of the poisson point process if the number of points has not been specified (absolute units).Defaults to 0.

        :return [list of tuples] generated_points: X and Y coordinates of the two-dimensional locations of the generated points, poisson distributed inside the hexagons -> [(x,y), (x,y), ...].
    """

    generated_points = list()

    hexagonal_points = np.array(hexagonal_points)  # Transform hexagonal_points (list) in np.array

    for i in range(0, len(hexagonal_points)):

        n = scipy.stats.poisson(alpha).rvs() if points_per_hexagon == 0 else points_per_hexagon

        for j in range(n):
            sub_point = scipy.stats.norm(loc=hexagonal_points[i, :2], scale=(sigma, sigma))
            generated_points.append(list(sub_point.rvs(2)))

    return np.array(generated_points)
